/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Summary
         * @description Counts, score/recovery statistics and recent runs from persisted experiments.
         */
        get: operations["get_dashboard_summary_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_experiments_get"];
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Experiment History
         * @description Filtered, sorted, paginated experiment summaries (no evidence payloads).
         *
         *     Repeat `state`, `fault_type` or `namespace` to match any of several values;
         *     `q` matches name, workload or namespace (case-insensitive substring).
         */
        get: operations["experiment_history_experiments_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_experiments__experiment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experiment_id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abort
         * @description Stop an active experiment: its own ChaosEngine only, then ABORTED.
         */
        post: operations["abort_experiments__experiment_id__abort_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experiment_id}/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture Experiment Baseline
         * @description Capture a steady-state baseline from Prometheus.
         *
         *     Success moves BASELINING -> INJECTING; a failed capture is recorded and the
         *     experiment stays in BASELINING so it can be retried. No fault is injected.
         */
        post: operations["capture_experiment_baseline_experiments__experiment_id__baseline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experiment_id}/inject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject Fault
         * @description Start the pod-delete fault via LitmusChaos (INJECTING experiments only).
         *
         *     Blocks until the target pods are confirmed deleted (-> OBSERVING) or the start
         *     fails/times out (-> INJECTION_FAILED, ChaosEngine stopped).
         */
        post: operations["inject_fault_experiments__experiment_id__inject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experiment_id}/observe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Observe Experiment
         * @description Advance observation by one bounded step (call repeatedly while in progress).
         *
         *     OBSERVING -> RECOVERING once Litmus finishes; RECOVERING -> COMPLETED when the
         *     recovery rule holds; -> UNKNOWN (with reason and cause) when it cannot be
         *     established. Read-only except stopping our own ChaosEngine on a Litmus timeout.
         */
        post: operations["observe_experiment_experiments__experiment_id__observe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experiment_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Experiment
         * @description Start the automatic lifecycle (idempotent).
         *
         *     Accepts a CREATED experiment, or one that passed POST /validate and has not
         *     started (BASELINING without a baseline). The orchestrator then drives it to
         *     COMPLETED/UNKNOWN and cleans up; follow it with GET /experiments/{id}.
         */
        post: operations["run_experiment_experiments__experiment_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experiment_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Experiment Score
         * @description The persisted Resilience Score (or the reason it was not scored).
         *
         *     `?version=v1` recomputes that methodology from the same stored evidence
         *     (deterministic; not persisted). 404 until the experiment has finished.
         */
        get: operations["get_experiment_score_experiments__experiment_id__score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experiment_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Experiment
         * @description Run static then cluster safety checks.
         *
         *     The outcome is the resulting state (BASELINING / VALIDATION_FAILED), not the HTTP status.
         */
        post: operations["validate_experiment_experiments__experiment_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Services
         * @description Deployments and StatefulSets outside system namespaces, with experiment history.
         *
         *     Replica counts are the controllers' own status (as `kubectl get` shows them).
         */
        get: operations["get_services_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{namespace}/{kind}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Service
         * @description Live pod health plus this workload's experiments, scores and tested faults.
         *
         *     If the cluster cannot be queried, history is still returned with
         *     health UNKNOWN and the error in `cluster_error`.
         */
        get: operations["get_service_services__namespace___kind___name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbortRequest */
        AbortRequest: {
            /** Reason */
            reason: string;
        };
        /** BaselineRead */
        BaselineRead: {
            availability: components["schemas"]["MetricGroupRead"];
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            client?: components["schemas"]["MetricGroupRead"] | null;
            /** Failure Reasons */
            failure_reasons: string[];
            requests: components["schemas"]["MetricGroupRead"];
            restarts: components["schemas"]["MetricGroupRead"];
            status: components["schemas"]["BaselineStatus"];
            /** Window Seconds */
            window_seconds: number;
        };
        /**
         * BaselineStatus
         * @enum {string}
         */
        BaselineStatus: "CAPTURED" | "FAILED";
        /** ChaosRead */
        ChaosRead: {
            /** Created At */
            created_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Engine Name */
            engine_name?: string | null;
            /** Experiment */
            experiment: string;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Injected At */
            injected_at?: string | null;
            /** Namespace */
            namespace?: string | null;
            pod_delete_mode?: components["schemas"]["PodDeleteMode"] | null;
            /** Provider */
            provider: string;
            /** Safety Policy */
            safety_policy?: string | null;
            /** Status */
            status?: {
                [key: string]: string | null;
            } | null;
            /** Stop Error */
            stop_error?: string | null;
            /** Stopped */
            stopped?: boolean | null;
            /**
             * Target Pods
             * @default []
             */
            target_pods: string[];
        };
        /**
         * CheckStatus
         * @enum {string}
         */
        CheckStatus: "PASSED" | "FAILED" | "ERROR" | "SKIPPED";
        /** DashboardSummary */
        DashboardSummary: {
            /** By State */
            by_state: {
                [key: string]: number;
            };
            client_outage_seconds: components["schemas"]["Distribution"];
            /** Namespaces */
            namespaces: components["schemas"]["NamespaceStats"][];
            outcomes: components["schemas"]["OutcomeCounts"];
            /** Recent */
            recent: components["schemas"]["ExperimentSummary"][];
            recovery_time_seconds: components["schemas"]["Distribution"];
            /** Score History */
            score_history: components["schemas"]["ScorePoint"][];
            scores: components["schemas"]["ScoreStats"];
            /** Total */
            total: number;
        };
        /** Distribution */
        Distribution: {
            /** Count */
            count: number;
            /** Maximum */
            maximum: number | null;
            /** Median */
            median: number | null;
            /** Minimum */
            minimum: number | null;
        };
        /** ExperimentCreate */
        ExperimentCreate: {
            /** Affected Replicas */
            affected_replicas: number;
            /** Description */
            description?: string | null;
            /** Duration Seconds */
            duration_seconds: number;
            fault_type: components["schemas"]["FaultType"];
            /** Name */
            name: string;
            /** @default GRACEFUL */
            pod_delete_mode: components["schemas"]["PodDeleteMode"];
            target: components["schemas"]["ExperimentTargetSchema"];
        };
        /** ExperimentPage */
        ExperimentPage: {
            /** Items */
            items: components["schemas"]["ExperimentSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ExperimentRead */
        ExperimentRead: {
            /** Affected Replicas */
            affected_replicas: number;
            baseline: components["schemas"]["BaselineRead"] | null;
            chaos: components["schemas"]["ChaosRead"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Duration Seconds */
            duration_seconds: number;
            fault_type: components["schemas"]["FaultType"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            observation: components["schemas"]["ObservationRead"] | null;
            /** Orchestration */
            orchestration?: {
                [key: string]: unknown;
            } | null;
            pod_delete_mode: components["schemas"]["PodDeleteMode"];
            score: components["schemas"]["ScoreRead"] | null;
            state: components["schemas"]["ExperimentState"];
            target: components["schemas"]["ExperimentTargetSchema"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            validation_result: components["schemas"]["ValidationResultRead"] | null;
        };
        /**
         * ExperimentState
         * @enum {string}
         */
        ExperimentState: "CREATED" | "VALIDATING" | "BASELINING" | "INJECTING" | "OBSERVING" | "RECOVERING" | "COMPLETED" | "VALIDATION_FAILED" | "INJECTION_FAILED" | "ABORTED" | "UNKNOWN";
        /**
         * ExperimentSummary
         * @description Slim experiment row for history lists and dashboards (no evidence JSON).
         */
        ExperimentSummary: {
            /** Affected Replicas */
            affected_replicas: number;
            /** Auto */
            auto: boolean;
            /** Client Outage Seconds */
            client_outage_seconds: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Seconds */
            duration_seconds: number;
            fault_type: components["schemas"]["FaultType"];
            /** Has Baseline */
            has_baseline: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Outcome Reason */
            outcome_reason: string | null;
            pod_delete_mode: components["schemas"]["PodDeleteMode"];
            score: components["schemas"]["ScoreSummary"] | null;
            state: components["schemas"]["ExperimentState"];
            target: components["schemas"]["ExperimentTargetSchema"];
            /** Time To Recovery Seconds */
            time_to_recovery_seconds: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ExperimentTargetSchema */
        ExperimentTargetSchema: {
            kind: components["schemas"]["WorkloadKind"];
            /** Name */
            name: string;
            /** Namespace */
            namespace: string;
        };
        /** FaultCoverage */
        FaultCoverage: {
            /** Completed */
            completed: number;
            fault_type: components["schemas"]["FaultType"];
            /**
             * Last Run At
             * Format: date-time
             */
            last_run_at: string;
            latest_score: components["schemas"]["LatestScore"] | null;
            pod_delete_mode: components["schemas"]["PodDeleteMode"];
            /** Runs */
            runs: number;
        };
        /**
         * FaultType
         * @enum {string}
         */
        FaultType: "pod-delete" | "pod-cpu-hog" | "pod-memory-hog" | "pod-network-latency";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LatestScore
         * @description The most recent experiment on this workload that produced a numeric score.
         */
        LatestScore: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /** Rating */
            rating: string | null;
            /** Score */
            score: number;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * LiveStatus
         * @description Pod-level status, read the same way safety validation reads it.
         */
        LiveStatus: {
            /** Desired Replicas */
            desired_replicas: number;
            /** Ready Pod Names */
            ready_pod_names: string[];
            /** Ready Pods */
            ready_pods: number;
            /** Running Pods */
            running_pods: number;
        };
        /** MetricGroupRead */
        MetricGroupRead: {
            /** Message */
            message: string;
            status: components["schemas"]["MetricStatus"];
            /** Values */
            values: {
                [key: string]: number | null;
            };
        };
        /**
         * MetricStatus
         * @enum {string}
         */
        MetricStatus: "OK" | "UNAVAILABLE" | "ERROR";
        /** NamespaceStats */
        NamespaceStats: {
            /** Completed */
            completed: number;
            /**
             * Last Activity
             * Format: date-time
             */
            last_activity: string;
            /** Namespace */
            namespace: string;
            /** Total */
            total: number;
        };
        /** ObservationRead */
        ObservationRead: {
            /** Evaluations */
            evaluations: number;
            /** Impact */
            impact?: {
                [key: string]: unknown;
            } | null;
            /** Last Error */
            last_error?: string | null;
            /** Litmus */
            litmus?: {
                [key: string]: unknown;
            } | null;
            /** Recovery */
            recovery?: {
                [key: string]: unknown;
            } | null;
            result: components["schemas"]["ObservationResultRead"];
            /** Rule */
            rule: string;
            /** Target */
            target?: {
                [key: string]: unknown;
            } | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ObservationResultRead */
        ObservationResultRead: {
            /** Cause */
            cause?: string | null;
            /** Reason */
            reason?: string | null;
            /** Reason Code */
            reason_code?: string | null;
            /** Status */
            status: string;
        };
        /** OutcomeCounts */
        OutcomeCounts: {
            /** Aborted */
            aborted: number;
            /** Active */
            active: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Undetermined */
            undetermined: number;
        };
        /**
         * PodDeleteMode
         * @description How pod-delete removes pods (maps to the vetted experiment's FORCE env).
         *
         *     GRACEFUL: default Kubernetes deletion; the pod's terminationGracePeriodSeconds
         *               applies (SIGTERM, then SIGKILL after the grace period).
         *     FORCE:    deletion with gracePeriodSeconds=0; containers are killed at once.
         * @enum {string}
         */
        PodDeleteMode: "GRACEFUL" | "FORCE";
        /** ScoreComponentRead */
        ScoreComponentRead: {
            /** Contribution */
            contribution: number;
            /** Effective Weight */
            effective_weight: number;
            /** Name */
            name: string;
            /** Normalized */
            normalized: number | null;
            /** Raw */
            raw: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
            /** Status */
            status: string;
            /** Weight */
            weight: number;
        };
        /** ScorePoint */
        ScorePoint: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /** Name */
            name: string;
            /** Namespace */
            namespace: string;
            /** Rating */
            rating: string | null;
            /** Score */
            score: number;
            /** Workload */
            workload: string;
        };
        /** ScoreRead */
        ScoreRead: {
            /** Cap Applied */
            cap_applied?: {
                [key: string]: number;
            } | null;
            /** Components */
            components: components["schemas"]["ScoreComponentRead"][];
            /** Explanation */
            explanation: string;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /** Rating */
            rating: string | null;
            /** Score */
            score: number | null;
            /** Status */
            status: string;
            /** Thresholds */
            thresholds?: {
                [key: string]: number;
            } | null;
            /** Version */
            version: string;
            /** Weights */
            weights?: {
                [key: string]: number;
            } | null;
        };
        /** ScoreStats */
        ScoreStats: {
            /** Average */
            average: number | null;
            /** By Rating */
            by_rating: {
                [key: string]: number;
            };
            /** Count */
            count: number;
            /** Maximum */
            maximum: number | null;
            /** Minimum */
            minimum: number | null;
            /** Not Recovered */
            not_recovered: number;
            /** Not Scored */
            not_scored: number;
            /** Other Versions */
            other_versions: number;
            /** Version */
            version: string;
        };
        /** ScoreSummary */
        ScoreSummary: {
            /** Rating */
            rating: string | null;
            /** Score */
            score: number | null;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ServiceDetail */
        ServiceDetail: {
            /** Cluster Error */
            cluster_error: string | null;
            /** Experiment Count */
            experiment_count: number;
            /** Experiments */
            experiments: components["schemas"]["ExperimentSummary"][];
            /** Faults */
            faults: components["schemas"]["FaultCoverage"][];
            /**
             * Health
             * @enum {string}
             */
            health: "HEALTHY" | "DEGRADED" | "UNAVAILABLE" | "SCALED_TO_ZERO" | "NOT_FOUND" | "UNKNOWN";
            kind: components["schemas"]["WorkloadKind"];
            latest_score: components["schemas"]["LatestScore"] | null;
            live: components["schemas"]["LiveStatus"] | null;
            /** Name */
            name: string;
            /** Namespace */
            namespace: string;
            /** Score History */
            score_history: components["schemas"]["ScorePoint"][];
            /** Score Version */
            score_version: string;
        };
        /** ServiceList */
        ServiceList: {
            /** Excluded Namespaces */
            excluded_namespaces: string[];
            /** Items */
            items: components["schemas"]["ServiceSummary"][];
        };
        /** ServiceSummary */
        ServiceSummary: {
            /** Available Replicas */
            available_replicas: number;
            /** Created At */
            created_at: string | null;
            /** Current Replicas */
            current_replicas: number;
            /** Desired Replicas */
            desired_replicas: number;
            /** Experiment Count */
            experiment_count: number;
            /**
             * Health
             * @enum {string}
             */
            health: "HEALTHY" | "DEGRADED" | "UNAVAILABLE" | "SCALED_TO_ZERO" | "NOT_FOUND" | "UNKNOWN";
            kind: components["schemas"]["WorkloadKind"];
            latest_experiment: components["schemas"]["ExperimentSummary"] | null;
            latest_score: components["schemas"]["LatestScore"] | null;
            /** Name */
            name: string;
            /** Namespace */
            namespace: string;
            /** Ready Replicas */
            ready_replicas: number;
        };
        /** ValidationCheckRead */
        ValidationCheckRead: {
            /** Message */
            message: string;
            /** Name */
            name: string;
            status: components["schemas"]["CheckStatus"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationResultRead */
        ValidationResultRead: {
            /** Cluster Checks */
            cluster_checks: components["schemas"]["ValidationCheckRead"][];
            /** Passed */
            passed: boolean;
            /** Policy */
            policy: {
                [key: string]: unknown;
            };
            /** Policy Selection */
            policy_selection?: {
                [key: string]: string;
            } | null;
            /** Static Checks */
            static_checks: components["schemas"]["ValidationCheckRead"][];
        };
        /**
         * WorkloadKind
         * @enum {string}
         */
        WorkloadKind: "Deployment" | "StatefulSet";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dashboard_summary_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    list_experiments_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"][];
                };
            };
        };
    };
    create_experiment_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_history_experiments_history_get: {
        parameters: {
            query?: {
                q?: string | null;
                state?: components["schemas"]["ExperimentState"][] | null;
                fault_type?: components["schemas"]["FaultType"][] | null;
                namespace?: string[] | null;
                sort?: "created_at" | "updated_at" | "name" | "score";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_experiments__experiment_id__abort_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbortRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_experiment_baseline_experiments__experiment_id__baseline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inject_fault_experiments__experiment_id__inject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observe_experiment_experiments__experiment_id__observe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_experiment_experiments__experiment_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_score_experiments__experiment_id__score_get: {
        parameters: {
            query?: {
                version?: string | null;
            };
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_experiment_experiments__experiment_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_services_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceList"];
                };
            };
        };
    };
    get_service_services__namespace___kind___name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                kind: components["schemas"]["WorkloadKind"];
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
