# OWNER: backend-teammate
# Intended: canonical experiment state machine. 11 states: CREATED, VALIDATING, BASELINING, INJECTING, OBSERVING, RECOVERING, COMPLETED, VALIDATION_FAILED, INJECTION_FAILED, ABORTED, UNKNOWN.
